Fix/audit fixes
ONSdigital/dp-files-api pull request #80
Opened 2022-06-22 09:38 UTC by redhug1

### What

Fix audit issues

### How to review

Inspect changes.
Run:
    make audit

### Who can review

Anyone

2022-06-22 14:35 UTC, rafahop requested changes

2022-06-22 15:23 UTC, redhug1 commented on go.mod
> +	github.com/prometheus/client_golang => github.com/prometheus/client_golang v1.12.2
Done

2022-06-22 15:23 UTC, redhug1 commented on ci/unit.yml
> +    tag: 1.18
Done

2022-06-27 07:49 UTC, rafahop approved these changes

2022-06-27 07:53 UTC, merged